Repository pathintegral-institute/mcp.science, pull requests merged in 2025-07, with the labels that each got.

#62 add a new function create_structure_from_cif
  servers/materials-project/src/materials_project/server.py
Labels: Review effort 2/5

#64 update description of StructureData
  servers/materials-project/src/materials_project/data_class.py
Labels: Review effort 3/5

#61 update user_config in manifest.json
  pyproject.toml
  servers/jupyter-act/manifest.json
  servers/materials-project/manifest.json
  servers/nemad/manifest.json
  servers/ssh-exec/manifest.json
Labels: Review effort 2/5, Possible security concern
