Repository pathintegral-institute/mcp.science, pull requests merged in 2025-06, with the labels that each got.

#46 [gpaw calculation] improve feedback for failure to LLM
  servers/gpaw-computation/server_package/gpaw_computation_server/gpaw_utils/lib.py
  servers/gpaw-computation/src/gpaw_computation/server.py
Labels: Review effort 2/5

#51 fix: updating dependency
  servers/web-fetch/pyproject.toml
  servers/web-fetch/src/web_fetch/__init__.py
  servers/web-fetch/src/web_fetch/fetch.py
  servers/web-fetch/uv.lock
Labels: Review effort 2/5

#52 Feature/mcp science alias
  pyproject.toml
  servers/tinydb/.python-version
  servers/tinydb/README.md
  servers/tinydb/pyproject.toml
  servers/tinydb/src/tinydb_server/__init__.py
  servers/tinydb/src/tinydb_server/main.py
  servers/tinydb/tests/test_main.py
  servers/tinydb/uv.lock
  src/mcp_science/__init__.py
  src/mcp_servers/__init__.py
  uv.lock
Labels: Review effort 4/5, codex-review-completed, Possible security concern

#54 Feature/mcp science alias updates
  .python-version
  pyproject.toml
  src/mcp_science/__init__.py
  uv.lock
Labels: Review effort 3/5, Possible security concern
